--OWNER, OBJECT_NAME and OBJECT_TYPE columns are mandatory
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE 
    FROM ALL_OBJECTS 
    WHERE OWNER in ('APPS')
    AND OBJECT_NAME like 'XXOPS%'
    AND OBJECT_TYPE IN ('SEQUENCE','PROCEDURE','PACKAGE','TRIGGER','VIEW',
    'FUNCTION','TABLE','TYPE', 'PACKAGE BODY', 'TYPE BODY', 
    'JAVA CLASS', 'JAVA SOURCE', 'MATERIALIZED VIEW')
UNION ALL
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE 
    FROM ALL_OBJECTS 
    WHERE OWNER in ('XXOPS')
    AND OBJECT_TYPE IN ('SEQUENCE','PROCEDURE','PACKAGE','TRIGGER','VIEW',
    'FUNCTION','TABLE','TYPE', 'PACKAGE BODY', 'TYPE BODY', 
    'JAVA CLASS', 'JAVA SOURCE', 'MATERIALIZED VIEW')
ORDER BY OWNER, OBJECT_TYPE